# Generated by Django 5.2.14 on 2026-05-20 02:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto'), ('transfer', 'Transferencia')], max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('installments', models.PositiveIntegerField(default=1, help_text='Number of installments for credit card purchases', validators=[django.core.validators.MinValueValidator(1)])),
                ('current_installment', models.PositiveIntegerField(default=1, help_text='Current installment number', validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField()),
                ('is_synced', models.BooleanField(default=True, help_text='Indicates if transaction has been synced from offline mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': 'transactions',
                'ordering': ['-date'],
            },
        ),
    ]
