# Generated by Django 5.2.14 on 2026-05-27 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_wallet',
            field=models.ForeignKey(blank=True, help_text='Destination wallet for transfers', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='wallets.wallet'),
        ),
    ]
